sudo: flase

# Requirements for Brian & NEST
addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    
    
language: python

python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=NEST
    - OMV_ENGINE=PyNEST
    - OMV_ENGINE=PyNN_Brian1
    - OMV_ENGINE=Brian
    - OMV_ENGINE=Brian2
    - OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNEURON
    - OMV_ENGINE=PyNN
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=Octave

install:
    - python setup.py install

script:
    - omv list-engines
    - cd utilities/tests
    - omv all -V
    - omv list-engines

